export { default as Home } from "./Home"
export {default as AboutUs} from "./AboutUs"
export {default as Price} from "./Price"
export {default as StyleDetail} from "./StyleDetail"
export {default as ProjectDetail} from "./ProjectDetail"